### ISSUE TITLE
L file

### ISSUE THREAD

**Issue by chaowoses** [VarunBanka/trojan#2]
i searched up batch trojan because i wanted to see if anyone else has made one and i found this thing
first of all if ur trying to target skids then at least obfuscate the code
second of all hmu we can make something a lot better >:)

**Comment by VarunBanka** [comment]
> i searched up batch trojan because i wanted to see if anyone else has made one and i found this thing first of all if ur trying to target skids then at least obfuscate the code second of all hmu we can make something a lot better >:)

Hi there
Thanks for letting me know, 
Actually Microsoft has fixed some things and yeah we can surely collaboration and make it a lot better .....
Thanks and Regards

**Comment by VarunBanka** [comment]
> i searched up batch trojan because i wanted to see if anyone else has made one and i found this thing first of all if ur trying to target skids then at least obfuscate the code second of all hmu we can make something a lot better >:)

hi there, 
i have updated the trojan
this time,  i have tried my level best to destroy the whole os
if you would like to collabrate with me on this project, please drop a mail at bankavarun18@gmail.com | varun870@outlook.com

**Comment by chaowoses** [comment]
do you have discord? i would rather use that

**Comment by VarunBanka** [comment]
> do you have discord? i would rather use that

Yep, I do have discord,
Varun#4158
